package engine

import (
	"encoding/json"
	"math"
	"os"
	"testing"
	"time"
)

// Golden test: the Go port must agree with the TypeScript that is currently
// running in production, to the paisa.
//
// testdata/golden.json is generated by bundling the real frontend engine and
// running it over the real seed profile:
//
//	npx esbuild internal/engine/testdata/golden.ts --bundle --platform=node \
//	    --format=esm --outfile=/tmp/golden.mjs && node /tmp/golden.mjs \
//	    > internal/engine/testdata/golden.json
//
// This is what makes the port safe to ship. A rewrite that "looks right" is
// how a finance app quietly starts showing different numbers on two screens;
// this test makes that a build failure instead of a support ticket.

type goldenFile struct {
	Runway struct {
		EssentialBurn     int64   `json:"essentialBurn"`
		DiscretionaryBurn int64   `json:"discretionaryBurn"`
		DebtService       int64   `json:"debtService"`
		TotalBurn         int64   `json:"totalBurn"`
		LiquidToday       int64   `json:"liquidToday"`
		Liquid1y          int64   `json:"liquid1y"`
		Locked            int64   `json:"locked"`
		Months            float64 `json:"months"`
		Target            float64 `json:"target"`
		Gap               int64   `json:"gap"`
		Status            string  `json:"status"`
	} `json:"runway"`
	Score struct {
		Total          int     `json:"total"`
		NetWorth       int64   `json:"netWorth"`
		FINumber       int64   `json:"fiNumber"`
		FIProgress     float64 `json:"fiProgress"`
		YearsToFreedom float64 `json:"yearsToFreedom"`
		Surplus        int64   `json:"surplus"`
		SavingsRate    float64 `json:"savingsRate"`
		Pillars        []struct {
			Key   string  `json:"key"`
			Score float64 `json:"score"`
			Max   float64 `json:"max"`
			State string  `json:"state"`
		} `json:"pillars"`
	} `json:"score"`
}

// seedProfile mirrors src/domain/seed.ts exactly, converted to paise.
func seedProfile() Profile {
	r := func(rupees float64) int64 { return int64(math.Round(rupees * 100)) }

	return Profile{
		Age:        29,
		Dependents: 2,
		Risk:       Balanced,
		Cash:       r(74_500),
		InHand:     r(1_24_000),
		AnnualBonu: r(1_80_000),
		EPFEmp:     r(5_400),
		EPFEmpr:    r(5_400),
		TermCover:  r(50_00_000),
		HealthCove: r(5_00_000),
		Expenses: []Expense{
			{"Rent", r(32_000), true},
			{"Groceries & cooking gas", r(11_000), true},
			{"Electricity, water, internet", r(4_200), true},
			{"Parents - monthly support", r(12_000), true},
			{"Commute & fuel", r(4_800), true},
			{"Medicines & checkups", r(2_400), true},
			{"Eating out & delivery", r(8_600), false},
			{"Shopping & lifestyle", r(6_500), false},
			{"Travel & weekends", r(4_000), false},
		},
		Subs: []int64{r(649), r(119), r(2_200), r(210), r(899), r(542), r(299)},
		Debts: []DebtItem{
			{r(84_000), 0.42, r(4_200), false},
			{r(2_10_000), 0.145, r(10_100), false},
			{r(1_40_000), 0.095, r(6_200), true},
		},
		Holdings: []Holding{
			{"NIFTY50", Equity, 420, r(261), 3},
			{"PPFCF", Equity, 310, r(79), 3},
			{"RELIANCE", Equity, 34, r(2_712), 1},
			{"HDFCBANK", Equity, 46, r(1_558), 1},
			{"ELSS", Equity, 190, r(46), 9999},
			{"PPF", Retirement, 1, r(2_04_000), 9999},
			{"NPS", Retirement, 1, r(71_400), 9999},
			{"LIQUID", Cash, 1, r(99_100), 1},
			{"SGB", Gold, 22, r(6_640), 30},
			{"BTC", Crypto, 0.038, r(52_80_000), 1},
			{"ETH", Crypto, 0.42, r(1_96_000), 1},
			{"ESG", ESG, 260, r(44), 3},
			{"CORPBOND", Debt, 1, r(61_300), 3},
		},
	}
}

func loadGolden(t *testing.T) goldenFile {
	t.Helper()
	raw, err := os.ReadFile("testdata/golden.json")
	if err != nil {
		t.Fatalf("read golden: %v (regenerate it - see the comment above)", err)
	}
	var g goldenFile
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("parse golden: %v", err)
	}
	return g
}

// Two paise of slack. The TypeScript accumulates in float rupees, so its
// totals carry a little representation error; Go is exact. Anything larger
// than this is a genuine logic divergence, not float noise.
const tolerancePaise = int64(2)

func assertPaise(t *testing.T, name string, got, want int64) {
	t.Helper()
	diff := got - want
	if diff < 0 {
		diff = -diff
	}
	if diff > tolerancePaise {
		t.Errorf("%s: got %d paise, want %d (diff %d)", name, got, want, diff)
	}
}

func assertFloat(t *testing.T, name string, got, want, tol float64) {
	t.Helper()
	if math.Abs(got-want) > tol {
		t.Errorf("%s: got %v, want %v (diff %v)", name, got, want, math.Abs(got-want))
	}
}

func TestRunwayMatchesTypeScript(t *testing.T) {
	g := loadGolden(t)
	got := ComputeRunway(seedProfile(), time.Now())

	assertPaise(t, "essentialBurn", got.EssentialBurn, g.Runway.EssentialBurn)
	assertPaise(t, "discretionaryBurn", got.DiscretionaryBurn, g.Runway.DiscretionaryBurn)
	assertPaise(t, "debtService", got.DebtService, g.Runway.DebtService)
	assertPaise(t, "totalBurn", got.TotalBurn, g.Runway.TotalBurn)
	assertPaise(t, "liquidToday", got.LiquidToday, g.Runway.LiquidToday)
	assertPaise(t, "liquid1y", got.Liquid1y, g.Runway.Liquid1y)
	assertPaise(t, "locked", got.Locked, g.Runway.Locked)
	assertPaise(t, "gap", got.Gap, g.Runway.Gap)

	assertFloat(t, "months", got.Months, g.Runway.Months, 1e-6)
	assertFloat(t, "target", got.Target, g.Runway.Target, 1e-9)

	if string(got.Status) != g.Runway.Status {
		t.Errorf("status: got %q, want %q", got.Status, g.Runway.Status)
	}
}

func TestFreedomScoreMatchesTypeScript(t *testing.T) {
	g := loadGolden(t)
	p := seedProfile()
	got := ComputeFreedomScore(p, ComputeRunway(p, time.Now()))

	if got.Total != g.Score.Total {
		t.Errorf("total: got %d, want %d", got.Total, g.Score.Total)
	}
	assertPaise(t, "netWorth", got.NetWorth, g.Score.NetWorth)
	assertPaise(t, "fiNumber", got.FINumber, g.Score.FINumber)
	assertPaise(t, "surplus", got.Surplus, g.Score.Surplus)

	assertFloat(t, "fiProgress", got.FIProgress, g.Score.FIProgress, 1e-9)
	assertFloat(t, "savingsRate", got.SavingsRate, g.Score.SavingsRate, 1e-9)
	assertFloat(t, "yearsToFreedom", got.YearsToFreedom, g.Score.YearsToFreedom, 1e-9)

	if len(got.Pillars) != len(g.Score.Pillars) {
		t.Fatalf("pillars: got %d, want %d", len(got.Pillars), len(g.Score.Pillars))
	}
	for i, want := range g.Score.Pillars {
		have := got.Pillars[i]
		if have.Key != want.Key {
			t.Errorf("pillar %d key: got %q, want %q", i, have.Key, want.Key)
		}
		assertFloat(t, "pillar "+want.Key+" score", have.Score, want.Score, 1e-9)
		if have.State != want.State {
			t.Errorf("pillar %s state: got %q, want %q", want.Key, have.State, want.State)
		}
	}
}

// A guard against the failure mode the whole paise convention exists to
// prevent: adding a rupee amount a thousand times should land exactly, and
// in float64 it does not.
func TestPaiseArithmeticIsExact(t *testing.T) {
	var totalPaise int64
	totalFloat := 0.0
	for i := 0; i < 1000; i++ {
		totalPaise += 10 // 0.10
		totalFloat += 0.10
	}
	if totalPaise != 10000 {
		t.Fatalf("integer paise drifted: %d", totalPaise)
	}
	if totalFloat == 100.0 {
		t.Skip("this float64 happened to land exactly; the point still stands")
	}
	t.Logf("float64 drift after 1000 additions of 0.10: %.20f vs 100.0", totalFloat)
}
